import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// if we want to use the title and description in the layout, we can use the metadata object to set them. This is useful for SEO and social media sharing. The metadata object can be exported from the layout file and used in the head of the document.
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// // };
// and for dynamic metadata, we can use the generateMetadata function to set the title and description based on the route parameters. This is useful for dynamic routes and pages that have different content based on the route parameters.
export const metadata = {
  title: {
    template: "%s | My App",
    default: "My App",
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header style={{ background: "teal" }}>Header</header>
        {children}
        <footer style={{ background: "teal" }}>Footer</footer>
      </body>
    </html>
  );
}
